# Generated by Django 6.0.3 on 2026-03-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField()),
            ],
        ),
    ]
